### ISSUE TITLE
Error: Cannot find module '@bconnorwhite/json-types'

### ISSUE THREAD

**Issue by quiqueg** [bconnorwhite/stringify-json-object#1]
Hello!

I was trying to use your package `npms-io-client` for a quick prototype, and I ran into the following error when invoking `client.packages([...])`:

```
Error: Cannot find module '@bconnorwhite/json-types'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/<redacted>/node_modules/stringify-json-object/build/index.js:6:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

After looking at the [published files on unpkg](https://unpkg.com/browse/stringify-json-object@1.0.6/build/index.js), it seems that there might be an issue with the release process which caused old files to be compiled and published. The `@bconnorwhite/json-types` package is not listed under the `stringify-json-object` dependencies, but is referenced in the published code.

Could you try releasing a new version?

**Comment by bconnorwhite** [comment]
Good catch, looks like I need to add a step to double check that imports are in the package.json dependencies.

I just published new versions of both packages. Can you check if that works for you?

**Comment by quiqueg** [comment]
@bconnorwhite works now, thank you!
